---
  - name: Install
    become: yes
    apt:
      name=nginx
      state=latest

  - name: Start
    become: yes
    service:
      name=nginx
      state=started
      enabled=true

  - name: Delete default configuration
    become: yes
    file:
      path=/etc/nginx/sites-enabled/default
      state=absent
    notify: Reload nginx

  - name: Create configuration
    become: yes
    template:
      src={{nginx_config_path}}
      dest=/etc/nginx/sites-available/{{domain_name}}

  - name: Activate domain {{domain_name}}
    become: yes
    file:
      src=/etc/nginx/sites-available/{{domain_name}}
      dest=/etc/nginx/sites-enabled/{{domain_name}}
      state=link
    notify: Reload nginx
...
