---
  - name: Install nodejs packages
    become: yes
    apt:
      name={{item}}
      state=latest
    with_items:
      - nodejs
      - npm

  - name: Symbolic link /usr/bin/nodejs to /usr/bin/node
    file:
      src=/usr/bin/nodejs
      dest=/usr/bin/node
      state=link

  - name: Install pm2
    become: yes
    command: npm install pm2 -g
...
