---
  - name: Setup server
    hosts: api
    remote_user: root
    vars:
      lock_ssh: no

    roles:
      - init
      - user
      - ssh
      - firewall
      - timezone
      - swap
      - nginx
      - pm2
...
