---
  - name: Setup server
    hosts: all
    remote_user: root

    roles:
      - init
      - user
      - timezone
      - swap
      - nginx

  - name: Setup api
    hosts: api
    remote_user: root

    roles:
      - jre
      - mongodb

  - name: Setup webapp
    hosts: webapp
    remote_user: root

    roles:
      - node

  - name: Configure ssh
    hosts: all
    remote_user: root

    roles:
      - ssh
      - firewall
...
