---
  - name: Write swapfile
    command: fallocate -l {{swapfile_size}} {{swapfile_location}} creates={{swapfile_location}}
    register: write_swapfile

  - name: Set swapfile permissions
    file: path={{swapfile_location}} mode=600

  - name: Create swapfile
    command: mkswap {{swapfile_location}}
    register: create_swapfile
    when: write_swapfile.changed

  - name: Enable swapfile
    command: swapon {{swapfile_location}}
    when: create_swapfile.changed

  - name: Add swapfile to /etc/fstab
    lineinfile: dest=/etc/fstab line="{{swapfile_location}} none swap sw 0 0" state=present
...
