---
  - name: Create directory
    file:
      path=/opt/jdk
      state=directory

  - name: Download Oracle archive
    get_url:
      url=http://download.oracle.com/otn-pub/java/jdk/8u77-b03/server-jre-8u77-linux-x64.tar.gz
      headers="Cookie:oraclelicense=accept-securebackup-cookie"
      dest=/home/deploy

  - name: Install
    unarchive:
      src=/home/deploy/server-jre-8u77-linux-x64.tar.gz
      dest=/opt/jdk
      copy=no

  - name: Setup java
    alternatives:
      name=java
      path=/opt/jdk/jdk1.8.0_77/bin/java
      link=/usr/bin/java

  - name: Setup javac
    alternatives:
      name=javac
      path=/opt/jdk/jdk1.8.0_77/bin/javac
      link=/usr/bin/javac
...
